### ISSUE TITLE
item.isDirectory is not a function

### ISSUE THREAD

**Issue by idkjs** [siffogh/reason-tree#1]
To reproduce, git clone repo.
Run `yarn install`.
Run `npm run build`.
Run `npm run start`.
In new terminal, same directory, run `node src/Demo.bs.js`

Output:
```sh
/Users/prisc_000/Downloads/reason-tree-master/src/Util.bs.js:22
                    if (item.isDirectory()) {
                             ^

TypeError: item.isDirectory is not a function
    at /Users/prisc_000/Downloads/reason-tree-master/src/Util.bs.js:22:30
    at Object._1 (/Users/prisc_000/Downloads/reason-tree-master/node_modules/bs-platform/lib/js/curry.js:64:12)
    at /Users/prisc_000/Downloads/reason-tree-master/node_modules/bs-platform/lib/js/list.js:589:21
    at filterItemsList (/Users/prisc_000/Downloads/reason-tree-master/src/Util.bs.js:27:22)
    at Object.printDir (/Users/prisc_000/Downloads/reason-tree-master/src/Util.bs.js:46:19)
    at Object.<anonymous> (/Users/prisc_000/Downloads/reason-tree-master/src/Demo.bs.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by siffogh** [comment]
As mentioned in the Readme, Node >= 10.x is required.
![image](https://user-images.githubusercontent.com/4761023/51668382-60d1f600-1fc2-11e9-9a51-a60104bf12d9.png)

**Comment by idkjs** [comment]
Using 10.8
```s
node -v
v10.8.0
```

**Comment by siffogh** [comment]
Sorry, Node >= 10.10.0
